on:
  workflow_call:
    inputs:
      disable-windows:
        description: Disable running tests on Windows
        type: boolean
        default: false
        required: false
      install-pnpm:
        description: Install pnpm before running tests
        type: boolean
        default: false
        required: false

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/iron", "lts/jod", "latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        if: ${{ inputs.install-pnpm }}
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  test_windows:
    if: ${{ !inputs.disable-windows }}
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ["lts/iron", "lts/jod", "latest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        if: ${{ inputs.install-pnpm }}
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
